(() => {
  const nodes = [
    ['Caduta controllata','stance',1,true,'','avanti, laterale, recupero in ginocchio','sicurezza prima della tecnica'],
    ['Posizione base','stance',1,true,'','neutral stance, ginocchia morbide, braccia libere','punto zero del sistema'],
    ['Peso laterale','stance',1,true,'Posizione base','statico, dinamico, dx/sx','primo trasferimento del carico'],
    ['Papera statica','stance',1,false,'Posizione base','apertura punte, chiusura talloni','prepara limone e transizioni'],
    ['Forbice base','stance',2,true,'Peso laterale','dx avanti, sx avanti','staggered stance stabile'],
    ['Affondo base','stance',2,true,'Forbice base','affondo alto, affondo basso','prepara T-stop, runner stop, slide'],
    ['Telemark tacco','stance',2,true,'Forbice base','dx/sx, statico, in glide','primo assetto longitudinale'],
    ['Telemark punta','stance',3,true,'Telemark tacco','dx/sx, in glide','assetto chiave per T-stop e curve'],
    ['Tacco-punta base','stance',3,false,'Telemark punta','heel-toe, toe-heel','ponte verso manual e transizioni sulle punte'],
    ['Monopedale assistito','stance',3,true,'Glide, Peso laterale','dx/sx, 1-3 secondi','primo appoggio singolo'],
    ['Closed stance base','stance',3,false,'Telemark punta','chiusura controllata','prepara curve strette e rotazioni'],
    ['Monopedale glide','stance',4,true,'Monopedale assistito','dx/sx, 5-8 secondi','appoggio singolo in movimento'],
    ['Affondo dinamico','stance',4,false,'Affondo base, Glide','ingresso/uscita, dx/sx','prepara runner stop e slide'],
    ['Eagle / open stance glide','stance',4,false,'Papera statica, Glide','apertura breve, uscita neutra','non ancora eagle tecnico'],
    ['Closed stance glide','stance',4,false,'Closed stance base, Glide','ingresso/uscita','assetto chiuso in movimento'],
    ['Edge interno / esterno base','stance',5,true,'Monopedale glide, Curva compasso','interno, esterno, dx/sx','sensibilita agli spigoli'],
    ['Monopedale in curva','stance',5,true,'Edge interno / esterno base','curva larga, entrambi i lati','prerequisito di carrellata e double push'],
    ['Tacco-punta glide','stance',5,false,'Tacco-punta base, Monopedale glide','heel-toe, toe-heel','controllo longitudinale ruote'],
    ['Forbice dinamica','stance',5,false,'Forbice base, Stride','cambio piede avanti','base per sprint e frenate'],
    ['Eagle tecnico','stance',6,false,'Eagle / open stance glide, Edge interno / esterno base','tenuta, curva ampia','apertura anche + controllo edge'],
    ['One-foot edge dinamico','stance',6,true,'Monopedale in curva','interno/esterno, dx/sx','monopedale non solo dritto'],
    ['Compressione / estensione','stance',6,false,'Affondo dinamico, Stride','basso-alto, alto-basso','prepara salti, slide, double push'],
    ['Toe manual glide','stance',7,false,'Tacco-punta glide, Monopedale glide','dx/sx, breve','una ruota anteriore in scorrimento'],
    ['Heel manual glide','stance',7,false,'Tacco-punta glide, Monopedale glide','dx/sx, breve','una ruota posteriore in scorrimento'],
    ['Manual bilaterale','stance',7,true,'Toe manual glide, Heel manual glide','switch naturale, dx/sx','controllo simmetrico'],
    ['Edge profondo','stance',7,true,'One-foot edge dinamico','interno/esterno, curva stretta','prepara slide e double push'],
    ['Manual in curva','stance',8,false,'Manual bilaterale, Edge profondo','heel/toe, dx/sx','manual con traiettoria'],
    ['Monopedale fakie','stance',8,false,'Fakie glide, Monopedale glide','dx/sx','retromarcia controllata su un piede'],
    ['Toe-heel switch','stance',8,false,'Manual bilaterale','cambio ruota senza appoggio pieno','ponte verso combo manual'],
    ['Eagle / closed transition','stance',8,false,'Eagle tecnico, Closed stance glide','open -> closed, closed -> open','controllo anche e assi'],
    ['Manual combo','stance',9,true,'Toe-heel switch, Manual in curva','toe->heel, heel->toe','continuita senza appoggio pieno'],
    ['Single wheel control','stance',9,true,'Manual combo, Monopedale fakie','glide lento, curve larghe','pre-master per heelwheel'],
    ['Edge transition monopedale','stance',9,false,'Edge profondo','interno<->esterno, dx/sx','cambio edge su un piede'],
    ['Single heelwheel manual (glide)','stance',10,true,'Single wheel control, Manual combo, Edge transition monopedale','dx/sx, switch, curva larga','skill master di equilibrio e glide'],

    ['Primi passi','gait',1,true,'Posizione base','V-walk, passi corti','ingresso al movimento'],
    ['Glide','gait',1,true,'Primi passi','due piedi','scorrimento base non saltabile'],
    ['Limone base','gait',1,true,'Papera statica, Glide','apertura/chiusura, lento','propulsione senza stacco'],
    ['Mezzo limone','gait',2,true,'Limone base, Peso laterale','dx/sx','una gamba guida, una stabilizza'],
    ['Mono spinta','gait',2,true,'Mezzo limone','dx/sx, spinta breve','prima spinta laterale'],
    ['Stroke','gait',2,true,'Mono spinta, Glide','spinta singola, recupero neutro','gesto di pattinata elementare'],
    ['Stride','gait',3,true,'Stroke, Monopedale assistito','ciclo alternato','base della pattinata completa'],
    ['Monopattino','gait',3,false,'Stroke, Forbice base','dx/sx','spinta ripetuta con gamba libera'],
    ['Glide monopedale','gait',3,true,'Monopedale assistito, Glide','dx/sx','ponte tra stance e gait'],
    ['Slalom base','gait',4,false,'Limone base, Curva compasso','piedi paralleli, ritmo lento','propulsione + traiettoria'],
    ['Fakie glide','gait',4,false,'Glide, Transizione in papera','lento, due piedi','retromarcia controllata'],
    ['Switch stance in andatura','gait',4,false,'Forbice base, Stride','piede opposto avanti','prima dimensione switch'],
    ['Pump / serpentina','gait',5,false,'Slalom base, Edge interno / esterno base','interno/esterno','genera velocita senza passo'],
    ['Fakie stride base','gait',5,false,'Fakie glide, Stride','passi corti','retromarcia con propulsione'],
    ['Sprint start','gait',5,false,'Forbice dinamica, Stroke','partenza breve','forza iniziale'],
    ['Fakie stride fluido','gait',6,false,'Fakie stride base','ritmo costante','variante avanzata di direzione'],
    ['Speed control','gait',6,true,'Stride, T-stop','accelerazione, decelerazione','controllo velocita senza panico'],
    ['One-foot push','gait',7,false,'Stride, One-foot edge dinamico','dx/sx','spinta con forte appoggio singolo'],
    ['Inside-edge push','gait',7,true,'Pump / serpentina, Monopedale in curva, Edge profondo','spinta interna','primo pezzo del double push'],
    ['Switch stride','gait',8,false,'Switch stance in andatura, Stride','piede opposto dominante','dimensione switch reale'],
    ['High speed glide','gait',8,false,'Speed control, Edge profondo','posizione bassa, rilascio','controllo a velocita alta'],
    ['Double push segmentato','gait',9,true,'Inside-edge push, Stride, Monopedale in curva','2-3 cicli','pre-master a velocita ridotta'],
    ['Double push bilaterale','gait',9,true,'Double push segmentato, Switch stride','entrambi i lati','simmetria del gesto'],
    ['Double push','gait',10,true,'Double push bilaterale, Stride, Edge transition monopedale','continuo, veloce, applicabile','skill master di propulsione'],

    ['Frenata limone','break',1,true,'Glide, Limone base','chiusura progressiva','prima gestione velocita'],
    ['Spazzaneve','break',2,true,'Frenata limone, Peso laterale','dx/sx carico, lento','attrito simmetrico'],
    ['T-stop','break',3,true,'Telemark punta, Glide, Spazzaneve','dx/sx','nodo chiave base'],
    ['Plow turn stop','break',3,false,'Spazzaneve, Curva compasso','curva + riduzione velocita','ponte verso runner stop'],
    ['Runner stop','break',4,true,'Affondo dinamico, Plow turn stop','dx/sx','stop direzionale dinamico'],
    ['Powerstop','break',4,true,'T-stop, Curva spinta','ingresso curvo','frenata rapida ma non slide piena'],
    ['Fakie T-stop','break',4,false,'Fakie glide, T-stop','dx/sx','variante di direzione'],
    ['Hockey stop base','break',5,false,'Powerstop, Edge interno / esterno base','parallelo parziale','ponte verso parallel'],
    ['Powerslide','break',6,true,'Powerstop, Fakie glide, Runner stop','dx/sx, fakie entry','prima slide riconoscibile'],
    ['Soul slide','break',6,false,'Affondo dinamico, Edge interno / esterno base, Curva carrellata avanzata','dx/sx','slide asimmetrica'],
    ['Magic slide','break',7,true,'Powerslide, Curva carrellata avanzata, Soul slide','dx/sx','controllo avanzato della pressione'],
    ['Slide exit control','break',7,true,'Powerslide, Soul slide','uscita in glide, uscita in curva','evita blocchi e cadute'],
    ['Switch powerslide','break',7,false,'Powerslide, Switch stance in andatura','lato debole','dimensione switch'],
    ['Slide bilaterale','break',8,true,'Magic slide, Switch powerslide','dx/sx, naturale/switch','controllo reale su entrambi i lati'],
    ['Slide combo base','break',8,false,'Slide exit control','powerslide->glide, soul->glide','continuita'],
    ['Parallel slide segmentata','break',9,true,'Hockey stop base, Magic slide, Slide bilaterale','ingresso, tenuta, uscita separati','pre-master'],
    ['Parallel slide','break',10,true,'Parallel slide segmentata, Speed control, Magic slide, Edge profondo','dx/sx, switch, uscita pulita','skill master di frenata'],

    ['Curva compasso','rotation',1,true,'Peso laterale, Glide','curva ampia dx/sx','sterzo base senza torsione'],
    ['Cambio direzione a passi','rotation',1,false,'Primi passi','piccoli passi, V-turn','cambio direzione sicuro'],
    ['Curva spinta','rotation',2,true,'Curva compasso, Stroke','dx/sx','spinta dentro traiettoria'],
    ['Transizione in papera','rotation',2,false,'Papera statica, Glide','frontale<->fakie lenta','primo cambio orientamento'],
    ['Mezzo giro su due piedi','rotation',2,false,'Curva compasso','dx/sx','rotazione a bassa velocita'],
    ['Curva carrellata base','rotation',3,true,'Curva spinta, Peso laterale','due piedi, edge larghi','curva senza passo'],
    ['Salto base / distacco','rotation',3,false,'Posizione base, Glide','stacco, atterraggio','dimensione distacco'],
    ['Curva carrellata','rotation',4,true,'Curva carrellata base, Monopedale glide','curve medie','edge + traiettoria'],
    ['Revert base','rotation',4,false,'Transizione in papera, Fakie glide','frontale<->fakie','cambio direzione senza salto'],
    ['Incrocio statico','rotation',4,false,'Forbice base, Curva compasso','passo sopra senza velocita','base tecnica del passo incrociato'],
    ['Transizione sulle punte','rotation',5,false,'Tacco-punta base, Tacco-punta glide','dx/sx','rotazione su asse stretto'],
    ['Carving base','rotation',5,true,'Curva carrellata, Edge interno / esterno base','interno/esterno','curva con edge consapevole'],
    ['Incrocio in curva assistito','rotation',5,true,'Incrocio statico, Curva carrellata','mano/ritmo assistito','primo incrocio reale ma non ancora skill finale'],
    ['Curva carrellata avanzata','rotation',6,true,'Carving base, Speed control','velocita, raggio stretto','prerequisito slide e double push'],
    ['Jump 180','rotation',6,false,'Salto base / distacco, Revert base','dx/sx','rotazione aerea base'],
    ['Cross step rhythm','rotation',7,true,'Incrocio in curva assistito, Monopedale in curva, Stride','2-3 incroci lenti','ritmo senza velocita alta'],
    ['Fakie revert fluido','rotation',7,false,'Revert base, Fakie stride base','entrambi i lati','dimensione fakie applicata'],
    ['Cross step bilaterale','rotation',8,true,'Cross step rhythm, Switch stride','senso orario/antiorario','entrambi i versi di curva'],
    ['Carving veloce','rotation',8,false,'Curva carrellata avanzata, Stride','velocita + edge','ponte verso crossover master'],
    ['Passo incrociato segmentato','rotation',9,true,'Cross step bilaterale, Carving veloce','ingresso, incrocio, spinta, uscita','pre-master'],
    ['Jump 360 segmentato','rotation',9,true,'Jump 180, Transizione sulle punte, Compressione / estensione, Edge transition monopedale','stacco, rotazione, landing','pre-master'],
    ['Passo incrociato','rotation',10,true,'Passo incrociato segmentato, Double push segmentato','continuo, veloce, entrambi i versi','skill master di curva propulsiva'],
    ['Jump 360','rotation',10,true,'Jump 360 segmentato, Speed control','dx/sx, atterraggio in glide','skill master di distacco e rotazione']
  ].map(([name, branch, level, key, prereq, variants, note]) => ({
    name, branch, level, key, note,
    variants: variants ? variants.split(',').map(v => v.trim()).filter(Boolean) : [],
    prereq: prereq ? prereq.split(',').map(v => v.trim()).filter(v => v && v !== '-') : []
  }));
  window.SKILLTREE_NODES = nodes;
})();
